<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="rPGPyGame" nsURI="http://www.example.org/rPGPyGame" nsPrefix="rPGPyGame">
  <eClassifiers xsi:type="ecore:EClass" name="Game">
    <eStructuralFeatures xsi:type="ecore:EReference" name="views" lowerBound="1" upperBound="-1"
        eType="#//view" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="view" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="MenuView" eSuperTypes="#//view">
    <eStructuralFeatures xsi:type="ecore:EReference" name="elements" upperBound="-1"
        eType="#//Element" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isFirst" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="GameView" eSuperTypes="#//view"/>
  <eClassifiers xsi:type="ecore:EClass" name="Button" abstract="true" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="text" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClassicButton" eSuperTypes="#//Button"/>
  <eClassifiers xsi:type="ecore:EClass" name="EditButton" eSuperTypes="#//Button"/>
  <eClassifiers xsi:type="ecore:EClass" name="NoSelectButton" eSuperTypes="#//Button"/>
  <eClassifiers xsi:type="ecore:EClass" name="Text" eSuperTypes="#//Element">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Element" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nameID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orderLayer" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colorBG" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="colorFG" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActionButton" eSuperTypes="#//Button">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dest" lowerBound="1" eType="#//view"/>
  </eClassifiers>
</ecore:EPackage>
